# How to get to Bressanone – Brixen

Bressanone (or Brixen) is in the bilingual province of Bolzano (Bozen) at 500 meters of altitude, in the Italian Alps, close to the Dolomites.


## By Train

Bressanone is on the international line between Munich (Germany) and Verona (Italy). Every train on this line stops in Bressanone. Moreover, there are many commuter connections from Innsbruck (Austria) and from Bolzano (Italy) to Bressanone.

The train from Verona P.ta Nuova to Bressanone takes about 2 hours, with frequent connections throughout the day. The train from Munich takes about 4 hours, with connections every 2 hours.

[Italian railways](https://www.trenitalia.com/en.html) --
[German railways](https://www.bahn.com/en) --
[Austrian railways](https://www.oebb.at/en)

## By Airplane

Several airports have reasonable train connections to Bressanone:

- Bolzano, Italy (BZO) 50 km (30 minutes by train)
- Innsbruck, Austria (INN) 80 km (1 hour by train)
- Verona, Italy (Valerio Catullo, VRN) 200 km
- Munich, Germany (Franz-Josef Strauss, MUC) 260 km (4 hours by train)
- Venezia, Italy (Marco Polo, VCE) 320 km
- Milano-Linate, Italy (LIN) 330 km
- Milano-Malpensa, Italy (MXP) 350 km

The closest large airport is Verona (Valerio Catullo) international airport. From Verona airport to the railway station Verona P.ta Nuova (see above) there is a [frequent shuttle bus service](https://www.atv.verona.it/flex/cm/pages/ServeBLOB.php/L/EN/IDPagina/90) throughout the day. From Verona to Bressanone it takes about 2 hours by train, and you have several trains per day (see above).

About Munich: please do not confuse Munich’s main airport (Franz-Josef Strauss) with what Ryanair calls “Munich West” (Memmingen) – the latter is far out in the Allg&auml;u, and it is not much fun coming from there by public transport; with a rental car, it is an option.

## Hotel information

You need to make your booking directly. There are many hotels and holiday rental options in Brixen, check the usual websites ([S&uuml;dtirol Info](https://www.suedtirol.info/en/accommodation/accommodation-search), booking, tripadvisor, airbnb, fewo-direct, ...). There is also a centrally located [Youth Hostel](https://www.jugendherberge.bz/en/bressanone/youth-hostel). Many of the course organisers and participants will be in the following places, which are short walking distance from the course venue and Brixen downtown (in general, Brixen is very compact and walkable):

 - Hotel Gruener Baum (Albero Verde)
 - Hotel Goldene Krone
 - Hotel Elephant
